dist: trusty

branches:
  - master
  - develop

language: php
php:
  - '7.1'

before_install:
  - sudo apt-get update
  - sudo apt-get install beanstalkd
  - yes '' | pecl install swoole
  - composer install

script:
  - vendor/bin/phpunit

cache:
  directories:
    - $HOME/.composer/cache


